feat: Updated to use DDI Activation Service
loopup/ct-integrated-reporting pull request #1
Opened 2023-06-26 15:40 UTC by duncanswsmith

# Description

Updated scripts to use DDI activation service.
SHER-896

TODO: Update Uris to use main branch prior to merge.

## Type of change

Please delete options that are not relevant.
- [ ] Bugfix
- [x] New feature
- [ ] Documentation
- [ ] Testing
- [ ] Other (please add options as needed for commit types)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
- [x] Tested on-premise script using CIT tenant running locally
- [x] Tested Azure deployment & script using QA tenant

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# Comments

Please start all comments with the correct emoji to denote the severity of the comment:

:sweat_drops: - No big deal, does not need fixing, just a comment
:hammer: - please fix before merging, once fixed can then be merged
:fire: - needs completely reworking and will need re-reviewing

2023-06-26 19:07 UTC, maureengillis reviewed
💦 Just reviewed for learning. Don't know if this matters but LoopUpHostedBillingScript_task.xml comes up with 'Binary File not shown' in the Files Changed area. Can view it using View File so not end of world.

2023-06-27 08:22 UTC, agoodsell5 requested changes

2023-06-27 08:22 UTC, agoodsell5 commented on README.md
>  ## LoopUp Hosted Billing Script deploy
🔨 Can we also change this to Self hosted ddi configuration reporting deploy

2023-06-27 08:22 UTC, agoodsell5 commented on scripts/Common/SelfHostedDdiConfigurationReporting.ps1
> +#$tenantId = (Get-CsTenant).TenantID
🔨 can remove?

2023-06-28 08:58 UTC, merged